version: '3.8'

services:
  painttest-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - HOSTNAME=0.0.0.0
      - PORT=3001
    volumes:
      # Persistent volume for all application data
      - painttest_data:/app
      # Mount specific database files to preserve data across rebuilds
      - ./painting_quotes_app.db:/app/painting_quotes_app.db
      - ./quotes.db:/app/quotes.db
      - ./painting_contractor.db:/app/painting_contractor.db
      - ./painting_quotes.db:/app/painting_quotes.db
    restart: unless-stopped
    container_name: painttest-app
    
volumes:
  # Named volume for persistent data storage
  painttest_data:
    driver: local